version: '3.7'
services:
  mysql:
    image: focker.ir/mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - '3307:3306'
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h mysql -u root -p$${MYSQL_ROOT_PASSWORD}" ]
      interval: 20s   # Increased interval
      timeout: 5s
      retries: 10     # Increased retries
#    volumes:
#      - db-data:/var/lib/mysql:cached
#    networks:
#      - app_network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    ports:
      - '8010:8000'
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'mysql://myuser:mypassword@172.17.0.1:3307/mydatabase'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      backend:
        condition: service_started
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network:
    driver: bridge
