"""Initial migration

Revision ID: 18d5020e86cd
Revises: 
Create Date: 2025-02-04 17:24:23.978750-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d5020e86cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('package_weight', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('picture', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('account_money',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('airline_review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_text', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('airline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['airline_id'], ['airline.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('flight',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('departure_city', sa.String(length=50), nullable=False),
    sa.Column('arrival_city', sa.String(length=50), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('price_per_adult', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('price_per_child', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('price_per_baby', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('is_international', sa.Boolean(), nullable=False),
    sa.Column('load_capacity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('class_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airline.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('idx_flights_cities', 'flight', ['departure_city', 'arrival_city'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('booking_date', sa.DateTime(), nullable=False),
    sa.Column('passengers', sa.JSON(), nullable=False),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('idx_bookings_flight', 'booking', ['flight_id'], unique=False)
    op.create_index('idx_bookings_user', 'booking', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bookings_user', table_name='booking')
    op.drop_index('idx_bookings_flight', table_name='booking')
    op.drop_table('booking')
    op.drop_index('idx_flights_cities', table_name='flight')
    op.drop_table('flight')
    op.drop_table('airline_review')
    op.drop_table('account_money')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('airline')
    # ### end Alembic commands ###
